const products=[
    {
        id:"1",
        image:require('../images/shirt.avif'),
        name:"Mens Shirt",
        price:"₹600",
        category:"view",
        description:"Regular Blue checked shirt with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"2",
        image :require('../images/pant.avif'),
        name:"Mens Pants Jeans ",
        price:" ₹840",   
        category:"view",
        description:"Regular jeans pants with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"3",
        image:require('../images/denim.avif'),
        name:"Mens Denim Shirt with Flap",
        price:"₹660",
        category:"view",
        description:"Regular denim shirt with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"4",
        image:require('../images/striped.avif'),
        name:"Mens Shirt Striped Cotton ",
        price:"₹1000",
        category:"view",
        description:"Regular denim shirt with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"5",
        image:require('../images/men-pants.avif'),
        name:"Mens Pants Fit Trousers",
        price:"₹1,599",
        category:"view",
        description:"Tapered Fit Trousers with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"6",
        image:require('../images/cargo.avif'),
        name:"Mens Pants Straight Fit Cargo ",
        price:"₹410",
        category:"view",
        description:"Men Straight Fit Cargo Pants with Insert Pockets with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"7",
        image:require('../images/coat men.avif'),
        name:"Mens Jacket Zip-Front ",
        price:"₹750",
        category:"view",
        description:"Men Zip-Front Jacket with Insert Pockets with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"8",
        image:require('../images/men coat 2.webp'),
        name:"Mens Jacket  Hooded ",
        price:"₹1,500",
        category:"view",
        description:"Zip-Front Hooded Jacket with Insert Pockets with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"9",
        image:require('../images/men blazers.avif'),
        name:"Mens Blazer Slim Fit ",
        price:"₹5,599",
        category:"view",
        description:"Slim Fit Blazer with Insert Pockets with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
    {
        id:"10",
        image:require('../images/men blazers2.avif'),
        name:"Mens Blazer Heathered ",
        price:"₹5,599",
        category:"view",
        description:"Heathered Blazer Jacket with Insert Pockets with 100% cotton Here's presenting a houseful of classic aviators, voguish wayfarers, chic cat-eye, and retro shades that you can own for a timeless look.",
    },
]
export default products